    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: ubuntu-22.04   # was ubuntu-20.04
            target: template_release
          - platform: windows
            os: windows-latest
            target: template_release
          - platform: macos
            os: macos-latest
            target: template_release
          - platform: android
            os: ubuntu-22.04   # was ubuntu-20.04
            target: template_release
          - platform: ios
            os: macos-latest
            target: template_release
